id: 141d27b6-25e3-47a1-8e15-dd0e37d489f0
version: 1
name: abcde
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0f11324c-63d4-48cd-849d-b5fb427bbf10
    type: start
    task:
      id: 0f11324c-63d4-48cd-849d-b5fb427bbf10
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
