id: 584e4016-cfdb-4491-891c-8b53413a0f69
version: 1
name: mmmmmmm
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 35bd0f1d-ebcf-4391-87fb-ddb10583f747
    type: start
    task:
      id: 35bd0f1d-ebcf-4391-87fb-ddb10583f747
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
