id: acaeb2f5-ac00-45b9-82c6-f04ad87fe597
version: 2
name: BB22
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
    type: start
    task:
      id: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: abd25f2b-eda5-4c0d-85f6-a1cf6feae8d5
    type: regular
    task:
      id: abd25f2b-eda5-4c0d-85f6-a1cf6feae8d5
      version: -1
      name: Ping
      description: Pings an IP or url address, to verify it's up
      script: Ping
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      address:
        simple: 6.6.6.6
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
