id: acaeb2f5-ac00-45b9-82c6-f04ad87fe597
version: 5
name: BB22
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
    type: start
    task:
      id: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 1a5015f3-938a-49a9-8ab0-b41f729bd8b8
    type: regular
    task:
      id: 1a5015f3-938a-49a9-8ab0-b41f729bd8b8
      version: -1
      name: print
      script: 6739e388-af6e-43cc-8549-d5a6b36008c6
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Hello
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
