id: acaeb2f5-ac00-45b9-82c6-f04ad87fe597
version: 3
name: BB22
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
    type: start
    task:
      id: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 8b5076b3-7335-4bf0-87e2-a0619e7f5ace
    type: regular
    task:
      id: 8b5076b3-7335-4bf0-87e2-a0619e7f5ace
      version: -1
      name: print
      script: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: HELLO
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 360
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 400,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
