id: 8513c901-eb5f-4c21-8e05-a3cbcbc21708
version: 1
name: aaaaaaaa
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 11262a61-c9cf-4273-83cf-bcc31a1db07b
    type: start
    task:
      id: 11262a61-c9cf-4273-83cf-bcc31a1db07b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
