id: acaeb2f5-ac00-45b9-82c6-f04ad87fe597
version: 4
name: BB22
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
    type: start
    task:
      id: 12bff09d-1618-41d1-8ccd-2cf2de14ef90
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: b138bd6b-d035-41b1-854e-72e889593d83
    type: regular
    task:
      id: b138bd6b-d035-41b1-854e-72e889593d83
      version: -1
      name: print
      script: 43dbd378-8d48-43da-8ffb-a350aecd12e4
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
